# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\123\Desktop\SimpleMVC\View\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 150)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_c = QtWidgets.QLineEdit(self.centralWidget)
        self.le_c.setMinimumSize(QtCore.QSize(60, 30))
        self.le_c.setObjectName("le_c")
        self.horizontalLayout.addWidget(self.le_c)
        self.lbl_plus = QtWidgets.QLabel(self.centralWidget)
        self.lbl_plus.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_plus.setObjectName("lbl_plus")
        self.horizontalLayout.addWidget(self.lbl_plus)
        self.le_d = QtWidgets.QLineEdit(self.centralWidget)
        self.le_d.setMinimumSize(QtCore.QSize(60, 30))
        self.le_d.setObjectName("le_d")
        self.horizontalLayout.addWidget(self.le_d)
        self.lbl_equal = QtWidgets.QLabel(self.centralWidget)
        self.lbl_equal.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_equal.setObjectName("lbl_equal")
        self.horizontalLayout.addWidget(self.lbl_equal)
        self.le_result = QtWidgets.QLineEdit(self.centralWidget)
        self.le_result.setMinimumSize(QtCore.QSize(60, 30))
        self.le_result.setReadOnly(True)
        self.le_result.setObjectName("le_result")
        self.horizontalLayout.addWidget(self.le_result)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_plus.setText(_translate("MainWindow", "+"))
        self.lbl_equal.setText(_translate("MainWindow", "="))
